### ISSUE TITLE
Error when translating nodes with nested paragraphs

### ISSUE THREAD

**Issue by SorenBonde** [backdrop-contrib/replicate_paragraphs#1]
When I try translating a node with nested paragraphs I get the following error:
`Error: Call to undefined function entity_metadata_wrapper() i replicate_paragraphs_clone_items() (linje 54 af /usr/www/users/supertqf/dtl/modules/replicate_paragraphs/replicate_paragraphs.module).
`

I have installed the following modules:
- Paragraphs 1.x-1.0.1
- Replicate 1.x-1.2
- Replicate Paragraphs 1.x-1.3

Backdrop version: 1.14.1

**Comment by SorenBonde** [comment]
Also tried installing the Entity Plus 1.x-1.0.3 module but then I get the following error:
`EntityMetadataWrapperException: Unknown data property [field_name]. in EntityStructureWrapper->getPropertyInfo() (line 335 of /modules/entity_plus/includes/entity_plus.wrapper.inc).`

**Comment by laryn** [comment]
@dBonde Have you done the same in a Drupal 7 site? Knowing whether this works in D7 would help me narrow down whether it is a porting issue or a flaw in the original module(s)...

**Comment by SorenBonde** [comment]
@laryn I can't remember. Been a while since I did a multilingual site in Drupal 7 so not sure I was using paragraphs back then.
Will try and test in Drupal 7 tomorrow and let you know.

**Comment by SorenBonde** [comment]
@laryn Just tested with a Drupal 7 site with nested paragraphs and I was able to translate without any issues. So it works in Drupal 7.

**Comment by laryn** [comment]
@dBonde Would you be willing to test the `nested` branch?
https://github.com/backdrop-contrib/replicate_paragraphs/tree/nested

**Comment by SorenBonde** [comment]
@laryn sorry for not getting back to you. The project had been put on hold for quite some time, but now I have been able to resume my work on the site.

Everything works great with the `nested` branch! :-)

Thanks a million! :-)
It saves me quite a lot of manual work when translating the pages! :-)

**Comment by laryn** [comment]
Great, thanks for reporting this and for help testing!
Closed via https://github.com/backdrop-contrib/replicate_paragraphs/pull/2
